# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qRDe5EwnDq8xleZlngxrsqWt8nih3JTc
"""

!pip install qiskit-aer

!pip install qiskit-aer
import string
from qiskit import QuantumCircuit
from qiskit_aer import Aer

def quantum_bit():
    qc = QuantumCircuit(1,1)
    qc.h(0)
    qc.measure(0,0)
    sim = Aer.get_backend('qasm_simulator')
    result = sim.run(qc, shots=1).result()
    return int(list(result.get_counts().keys())[0])

def random_char():
    chars = string.ascii_letters + string.digits + "!@#$%^&*"
    index = 0
    for _ in range(7): #7 bits to get 0-127
        index = (index << 1) | quantum_bit()
    return chars[index % len(chars)]

password = "".join(random_char() for _ in range(12))
print("Quantum-generated password:", password)